<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
	<PropertyGroup>
		<Version>15.10000</Version>
		<LangVersion>preview</LangVersion>
		<Author>croizat</Author>
		<Name>saewoo's Glamour Log</Name>
		<InternalName>GlamourLog</InternalName>
		<Punchline>Gotta collect 'em all</Punchline>
		<Description>A log for all your glamours and other glam-related tweaks</Description>
		<RepoUrl>https://github.com/Jaksuhn/ffxiv_glamourlog</RepoUrl>
		<IconUrl>https://puni.sh/api/plugins/icon/136</IconUrl>
		<Tags>glamour</Tags>

		<LocalCS>true</LocalCS>
	</PropertyGroup>

    <ItemGroup>
		<None Include="DalamudPackager.targets" />
    </ItemGroup>

	<PropertyGroup Condition="'$(LocalCS)'=='true'">
		<DefineConstants>LOCAL_CS</DefineConstants>
		<Use_Dalamud_FFXIVClientStructs>false</Use_Dalamud_FFXIVClientStructs>
	</PropertyGroup>

	<ItemGroup Condition="'$(LocalCS)'=='true'">
		<ProjectReference Include="..\FFXIVClientStructs\FFXIVClientStructs\FFXIVClientStructs.csproj" Private="True" />
		<ProjectReference Include="..\FFXIVClientStructs\InteropGenerator.Runtime\InteropGenerator.Runtime.csproj" Private="True" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="croizat.clib" Version="1.0.76" />
		<PackageReference Include="KamiToolKit" Version="2.2.9" />
	</ItemGroup>
</Project>
